name: 우산 이슈 추가 ☂️
description: 여러 이슈 작업을 관리합니다.
title: "☂️ "

labels: [":open_umbrella: umbrella"]
body:
  - type: textarea
    id: tasklist
    attributes:
      label: 이슈 및 할 일 추가
      description: |
        1. [tasklist](https://docs.github.com/ko/issues/managing-your-tasks-with-tasklists/creating-a-tasklist)
        2. 각 체크박스를 이슈로 전환하고, 시작 및 마감 날짜를 설정합니다.
        3. [프로젝트 로드맵](https://github.com/LastExTrascendence/frontend/projects?query=is%3Aopen)에서 전체 진행 과정을 확인합니다.

      value: |
        ```[tasklist]
        ### 할 일
        - [ ] 작업 1
        - [ ] 작업 2
        ```
    validations:
      required: true
