const chats = [
  {
    id: 1,
    channel: "온라인바카라〈abc.com〉【코드mama】",
    creator: "miyu",
    users: "23/48",
    type: "private",
  },
  {
    id: 2,
    channel: "파이썬1:1초보만",
    creator: "chanheki",
    users: "1/2",
    type: "public",
  },
  {
    id: 3,
    channel: "7인입구막기너만오면고",
    creator: "jaeyojun",
    users: "1/2",
    type: "public",
  },
  {
    id: 4,
    channel: "무료바카라게임➍➎➊➒➍➋›해외배팅사이트",
    creator: "yeomin",
    users: "1/2",
    type: "private",
  },
  {
    id: 5,
    channel: "42seoul_global_random",
    creator: "jusohn",
    users: "1/2",
    type: "private",
  },
  {
    id: 6,
    channel: "박보영너만보영",
    creator: "chanheki",
    users: "1/2",
    type: "public",
  },
  {
    id: 7,
    channel: "test1",
    creator: "jaeyojun",
    users: "1/2",
    type: "public",
  },
  {
    id: 8,
    channel: "test2",
    creator: "yeomin",
    users: "1/2",
    type: "public",
  },
  {
    id: 9,
    channel: "파이썬1:1초보만-2",
    creator: "chanheki",
    users: "1/2",
    type: "public",
  },
  {
    id: 10,
    channel: "7인입구막기너만오면고-2",
    creator: "jaeyojun",
    users: "1/2",
    type: "public",
  },
  {
    id: 11,
    channel: "무료바카라게임➍➎➊➒➍➋›해외배팅사이트-2",
    creator: "yeomin",
    users: "1/2",
    type: "private",
  },
  {
    id: 12,
    channel: "42seoul_global_random-2",
    creator: "jusohn",
    users: "1/2",
    type: "private",
  },
  {
    id: 13,
    channel: "박보영너만보영-2",
    creator: "chanheki",
    users: "1/2",
    type: "public",
  },
  {
    id: 14,
    channel: "test1-2",
    creator: "jaeyojun",
    users: "1/2",
    type: "public",
  },
  {
    id: 15,
    channel: "test2-2",
    creator: "yeomin",
    users: "1/2",
    type: "public",
  },
];

export default chats;
